<?php
$items = [array(
    'data' => 'desserts',
    'mini' => false,
    'cat'=> array("EN"=> 'Desserts', "RU"=> 'Десерты'),
    'items' => array(
    array(
      'id'=> 89,
      'name'=>array('EN'=> 'Warm apple pie with an ice cream scoop', 'RU'=>"Теплый яблочный пирог с шариком мороженого") ,
      'title'=>array('EN'=> 'Homemade apple and puff pastry pie, ice cream scoop, nuts', 'RU'=>"Домашний пирог из яблок и слоеного теста, шарик мороженого, орехи") ,
      'price'=> 499,
      'count'=> 1,
      'grams'=> 210,
      'img'=> "",
    ),
    array(
      'id'=> 90,
      'name'=>array('EN'=> 'Chocolate fondant with vanilla ice cream', 'RU'=>"Шоколадный фондан с ванильным мороженым"),
      'title'=>array('EN'=> 'Dark chocolate fondant, vanilla ice cream scoop', 'RU'=>"Фондан из темного шоколада, шарик ванильного мороженого"),
      'price'=> 599,
      'count'=> 1,
      'grams'=> 270,
      'img'=> "",
    )
    ),
),

   array(
    'data' => 'susi',
    'mini' => true,
    'cat'=>array("EN"=>'Sushi',"RU"=>'Суши'),
    'items' => array(
    array(
      'id'=> 1,
      'name'=>array('EN'=> 'Sashimi Shrimp', 'RU'=> 'Сашими креветка'),
      'title'=> array('EN'=> 'Shrimp, wasabi, ginger', 'RU'=>"Креветка, васаби, имбирь"),
      'price'=> 759,
      'count'=> 1,
      'grams'=> 60,
      'img'=> "",
    ),
    array(
      'id'=> 2,
      'name'=>array('EN'=> 'Salmon Sashimi', 'RU'=> "Сашими лосось"),
      'title'=>array('EN'=> 'Salmon, wasabi, ginger', 'RU'=> "Лосось, васаби, имбирь"),
      'price'=> 799,
      'count'=> 1,
      'grams'=> 60,
      'img'=> "",
    ),
    array(
      'id'=> 3,
      'name'=>array('EN'=> 'Tuna Sashimi', 'RU'=> "Сашими тунец"),
      'title'=>array('EN'=> 'Tuna, wasabi, ginger', 'RU'=> "Тунец, васаби, имбирь"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 60,
      'img'=> "",
    ),
    array(
      'id'=> 4,
      'name'=>array('EN'=> 'Sashimi eel', 'RU'=> "Сашими угорь"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 60,
      'img'=> "",
    ),
    array(
      'id'=> 5,
      'name'=>array('EN'=> 'Spicy crab', 'RU'=> "Спайси с крабом"),
      'title'=>array('EN'=> 'Crab, rice, nori, spicy sauce', 'RU'=> "Краб, рис, нори, спайси соус"),
      'price'=> 299,
      'count'=> 1,
      'grams'=> 35,
      'img'=> "",
    ),
    array(
      'id'=> 6,
      'name'=>array('EN'=> 'Spicy shrimp', 'RU'=> "Спайси с креветкой"),
      'title'=>array('EN'=> 'Shrimp, rice, nori, spicy sauce', 'RU'=> "Креветка, рис, нори, спайси соус"),
      'price'=> 229,
      'count'=> 1,
      'grams'=> 35,
      'img'=> "",
    ),
    array(
      'id'=> 7,
      'name'=>array('EN'=> 'Spicy salmon', 'RU'=> "Спайси с лососем"),
      'title'=>array('EN'=> 'Salmon, rice, nori, spicy sauce', 'RU'=> "Лосось, рис, нори, спайси соус"),
      'price'=> 229,
      'count'=> 1,
      'grams'=> 35,
      'img'=> "",
    ),
    array(
      'id'=> 8,
      'name'=>array('EN'=> 'Spicy tuna', 'RU'=> "Спайси с тунцом"),
      'title'=>array('EN'=> 'Tuna, rice, nori, spicy sauce', 'RU'=> "Тунец, рис, нори, спайси соус"),
      'price'=> 299,
      'count'=> 1,
      'grams'=> 35,
      'img'=> "",
    ),
    array(
      'id'=> 9,
      'name'=>array('EN'=> 'Spicy with eels', 'RU'=> "Спайси с угрем"),
      'title'=>array('EN'=> 'Eel, rice, nori, spicy sauce', 'RU'=> "Угорь, рис, нори, спайси соус"),
      'price'=> 299,
      'count'=> 1,
      'grams'=> 35,
      'img'=> "",
    ),
    array(
      'id'=> 10,
      'name'=>array('EN'=> 'Sushi with shrimp', 'RU'=> "Суши с креветкой"),
      'title'=>array('EN'=> 'Shrimp, rice', 'RU'=> "Креветка, рис"),
      'price'=> 199,
      'count'=> 1,
      'grams'=> 30,
      'img'=> "",
    ),
    array(
      'id'=> 11,
      'name'=>array('EN'=> 'Sushi with salmon', 'RU'=> "Суши с лососем"),
      'title'=>array('EN'=> 'Salmon, rice', 'RU'=> "Лосось, рис"),
      'price'=> 199,
      'count'=> 1,
      'grams'=> 30,
      'img'=> "",
    ),
    array(
      'id'=> 12,
      'name'=>array('EN'=> 'Sushi with tuna', 'RU'=> "Суши с тунцом"),
      'title'=>array('EN'=> 'Tuna, rice', 'RU'=> "Тунец, рис"),
      'price'=> 259,
      'count'=> 1,
      'grams'=> 30,
      'img'=> "",
    ),
    array(
      'id'=> 13,
      'name'=>array('EN'=> 'Sushi with eel', 'RU'=> "Суши с угрем"),
      'title'=>array('EN'=> 'Eel, rice', 'RU'=> "Угорь, рис"),
      'price'=> 259,
      'count'=> 1,
      'grams'=> 30,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'breakfast',
    'mini' => false,
    'cat'=>array("EN"=>'Breakfasts until 14:00',"RU"=>'Завтраки до 14:00'),
    'items' => array(
    array(
      'id'=> 14,
      'name'=>array('EN'=> 'Bruschetta with poached egg, avocado and salmon', 'RU'=>"Брускетта с яйцом пашот, авокадо и лососем"),
      'title'=>array('EN'=> 'Grain bread, salted salmon, poached egg, avocado, mixed salad', 'RU'=>"Хлеб зерновой, лосось слабосоленый, яйцо пашот, авокадо, микс салатов"),
      'price'=> 679,
      'count'=> 1,
      'grams'=> 180,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3401132/3e3083cbae1c4a9a815a5a88db9ed4ed/450x300",
    ),
    array(
      'id'=> 15,
      'name'=>array('EN'=> 'Zucchini dredges with salmon and cream sauce', 'RU'=>"Драники из цукини с лососем и сливочным соусом") ,
      'title'=>array('EN'=> 'Zucchini, egg, lightly salted salmon, cream sauce', 'RU'=>"Цукини, яйцо, лосось слабосоленый, соус сливочный"),
      'price'=> 729,
      'count'=> 1,
      'grams'=> 160,
      'img'=> "https://avatars.mds.yandex.net/get-eda/2050703/d0fe6a0797b741d1bf85f7b40e079136/450x300",
    ),
    array(
      'id'=> 16,
      'name'=>array('EN'=> 'Scramble with prosciutto and tomatoes', 'RU'=>"Скрамбл с прошутто и помидорами"),
      'title'=>array('EN'=> 'Chicken eggs, prosciutto, tomatoes', 'RU'=>"Яйца куриные, прошутто, помидоры"),
      'price'=> 499,
      'count'=> 1,
      'grams'=> 140,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3813301/2309447194f24bc482ee55189d530799/450x300",
    ),
    array(
      'id'=> 17,
      'name'=>array('EN'=> 'Tornado omelette with quinoa and vegetables', 'RU'=>"Торнадо омлет с киноа и овощами"),
      'title'=>array('EN'=> 'Chicken egg, quinoa, tomato, avocado, cucumber', 'RU'=>"Яйцо куриное, киноа, томат, авокадо, огурец"),
      'price'=> 349,
      'count'=> 1,
      'grams'=> 170,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3507285/e18b21e6ceaa4236a45d5e46a2758a7f/450x300",
    ),
    array(
      'id'=> 18,
      'name'=>array('EN'=> 'Eggs Benedict with salmon on a brioche bun', 'RU'=>"Яйцо бенедикт с лососем на булочке бриошь"),
      'title'=>array('EN'=> 'Brioche bun, lightly salted salmon, chicken egg, hollandaise sauce', 'RU'=>"Булочка бриошь, лосось слабосоленый, яйцо куриное, соус голландский"),
      'price'=> 789,
      'count'=> 1,
      'grams'=> 220,
      'img'=> "https://avatars.mds.yandex.net/get-eda/2353725/9084d606a70e418b9e0a52ce76e08f80/450x300",
    ),
    array(
      'id'=> 19,
      'name'=>array('EN'=> 'Oatmeal', 'RU'=>"Овсяная каша"),
      'title'=>array('EN'=> 'Oat flakes, milk', 'RU'=>"Овсяные хлопья, молоко"),
      'price'=> 229,
      'count'=> 1,
      'grams'=> 229,
      'img'=> "",
    ),
    array(
      'id'=> 20,
      'name'=>array('EN'=> 'An omelet of three eggs', 'RU'=>"Омлет из трех яиц"),
      'title'=>array('EN'=> 'Chicken eggs', 'RU'=>"Яйца куриные"),
      'price'=> 159,
      'count'=> 1,
      'grams'=> 159,
      'img'=> "",
    ),
    array(
      'id'=> 21,
      'name'=>array('EN'=> 'Rice porridge', 'RU'=>"Рисовая каша"),
      'title'=>array('EN'=> 'Rice Krispies, milk', 'RU'=>"Рисовые хлопья, молоко"),
      'price'=> 299,
      'count'=> 1,
      'grams'=> 270,
      'img'=> "",
    ),
    array(
      'id'=> 22,
      'name'=>array('EN'=> 'Cheesecakes with melted milk and sour cream', 'RU'=>"Сырники из топленого молока со сметаной") ,
      'title'=>array('EN'=> 'Cottage cheese, flour, chicken egg, sour cream', 'RU'=>"Творог, мука, яйцо куриное, сметана") ,
      'price'=> 349,
      'count'=> 1,
      'grams'=> 349,
      'img'=> "",
    ),
    array(
      'id'=> 23,
      'name'=>array('EN'=> 'Three egg scrambled eggs', 'RU'=>"Яишница из трех яиц") ,
      'title'=>array('EN'=> 'Chicken eggs', 'RU'=>"Яйца куриные") ,
      'price'=> 159,
      'count'=> 1,
      'grams'=> 120,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'roll',
    'mini' => true,
    'cat'=>array("EN"=>'Rolls',"RU"=>'Роллы'),
    'items' => array(
    array(
      'id'=> 24,
      'name'=> array('EN'=> 'Maki and avocado', 'RU'=> "Маки с авокадо"),
      'title'=>array('EN'=> 'Avocado, rice, nori', 'RU'=> "Авокадо, рис, нори"),
      'price'=> 299,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    array(
      'id'=> 25,
      'name'=>array('EN'=> 'Maki with salmon', 'RU'=> "Маки с лососем"),
      'title'=>array('EN'=> 'Salmon, rice, nori', 'RU'=> "Лосось, рис, нори"),
      'price'=> 359,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    array(
      'id'=> 26,
      'name'=>array('EN'=> 'Poppies with cucumber', 'RU'=> "Маки с огурцом"),
      'title'=>array('EN'=> 'Cucumber, rice, nori', 'RU'=> "Огурец, рис, нори"),
      'price'=> 249,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    array(
      'id'=> 27,
      'name'=>array('EN'=> 'Tuna maki', 'RU'=> "Маки с тунцом") ,
      'title'=>array('EN'=> 'Tuna, rice, nori', 'RU'=> "Тунец, рис, нори") ,
      'price'=> 399,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    array(
      'id'=> 28,
      'name'=>array('EN'=> 'Poppies with eel', 'RU'=> "Маки с угрем"),
      'title'=>array('EN'=> 'Eel, rice, nori', 'RU'=> "Угорь, рис, нори"),
      'price'=> 399,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    array(
      'id'=> 29,
      'name'=>array('EN'=> 'California Roll', 'RU'=> "Ролл Калифорния") ,
      'title'=>array('EN'=> 'Crab, rice, Japanese mayonnaise, avocado, nori, tobiko', 'RU'=> "Краб, рис, японский майонез, авокадо, нори, тобико"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "",
    ),
    array(
      'id'=> 30,
      'name'=>array('EN'=> 'Roll Canada', 'RU'=> "Ролл Канада") ,
      'title'=>array('EN'=> 'Salmon, eel, cream cheese, avocado, nori, unagi yuzu sauce, sesame, rice', 'RU'=> "Лосось, угорь, сливочный сыр, авокадо, нори, соус унаги юдзу, кунжут, рис"),
      'price'=> 999,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "",
    ),
    array(
      'id'=> 31,
      'name'=>array('EN'=> 'Philadelphia Roll', 'RU'=> "Ролл Филадельфия"),
      'title'=>array('EN'=> 'Salmon, cream cheese, rice, avocado, nori', 'RU'=> "Лосось, сливочный сыр, рис, авокадо, нори"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "",
    ),
    array(
      'id'=> 32,
      'name'=>array('EN'=> 'Seared salmon roll', 'RU'=> "Ролл с опаленным лососем") ,
      'title'=>array('EN'=> 'Salmon, eel, avocado, nori, tobiko, unagi yuzu sauce, sesame, spicy sauce, rice', 'RU'=> "Лосось, угорь, авокадо, нори, тобико, соус унаги юдзу, кунжут, спайси соус, рис"),
      'price'=> 999,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "",
    ),
    )
),
  
   array(
    'data' => 'noodles',
    'mini' => false,
    'cat'=>array("EN"=>'Noodles',"RU"=>'Лапша' ),
    'items' => array(
    array(
      'id'=> 33,
      'name'=>array('EN'=>'Buckwheat noodles with chicken in Asian sauce', 'RU'=>"Гречневая лапша с курицей в азиатском соусе"), 
      'title'=>array('EN'=>'Buckwheat noodles, chicken thigh bell peppers, carrots, zucchini, pods', 'RU'=>"Лапша гречневая, куриное бедро болгарский перец, морковь, цукини, стручки"),
      'price'=> 559,
      'count'=> 1,
      'grams'=> 300,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3585205/87d4d6f75bdf4e92ae27b477224d4773/450x300",
    ),
    array(
      'id'=> 37,
      'name'=>array('EN'=>'Rice noodles with tiger shrimps', 'RU'=>"Рисовая лапша с тигровыми креветками"),
      'title'=>array('EN'=>'Rice noodles, tiger shrimp, bell peppers, carrots, zucchini', 'RU'=>"Рисовая лапша, тигровые креветки, болгарский перец, морковь, цукини"),
      'price'=> 659,
      'count'=> 1,
      'grams'=> 320,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3534679/c4b043de7c194c62adb9ca24c8ef9ba6/450x300",
    ),
    )
),
  
    array(
    'data' => 'pasta',
    'mini' => false,
    'cat'=>array("EN"=>'Pasta and risotto',"RU"=>'Паста и ризотто'),
    'items' => array(
    array(
      'id'=> 34,
      'name'=>array('EN'=>'Gnocchi with burrata and red caviar', 'RU'=>"Ньоки с бурратой и красной икрой"), 
      'title'=>array('EN'=>'Gnocchi, burrata, red caviar', 'RU'=>"Ньоки, буррата, красная икра"), 
      'price'=> 799,
      'count'=> 1,
      'grams'=> 230,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3559865/986b89f2f917469eb24d9ad6679c161f/450x300",
    ),
    array(
      'id'=> 35,
      'name'=>array('EN'=>'Penne with beef, porcini mushrooms and truffle sauce', 'RU'=>"Пенне с говядиной, белыми грибами и трюфельным соусом"), 
      'title'=>array('EN'=>'Penne, beef, parmesan cheese, white mushrooms, white wine, cream', 'RU'=>"Пенне, говяжья вырезка, сыр пармезан, белые грибы, вино белое, сливки"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 350,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3529621/42d7ce5ef29040088492e631d6cf1a51/450x300",
    ),
    array(
      'id'=> 36,
      'name'=>array('EN'=>'Risotto with duck in truffle sauce', 'RU'=>"Ризотто с уткой в трюфельном соусе"), 
      'title'=>array('EN'=>'Arborio rice, duck, baked pumpkin', 'RU'=>"Рис арборио, утка, тыква запеченная"),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 220,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3583740/5e50ff6dcc76470a8adc75f5e933d633/450x300",
    ),
   
    array(
      'id'=> 38,
      'name'=>array('EN'=>'Tagliatelle with seafood', 'RU'=>"Тальятелле с морепродуктами"), 
      'title'=>array('EN'=>'Tagliatelle, squid, shrimp, mussels, octopus, white wine', 'RU'=>"Тальятелле, кальмары, кревертки, мидии, осьминог, вино белое"), 
      'price'=> 999,
      'count'=> 1,
      'grams'=> 390,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3593277/a20e1f6f5a46465c9b66cfc565801bdb/450x300",
    ),
    array(
      'id'=> 39,
      'name'=>array('EN'=>'Risotto with porcini mushrooms', 'RU'=>"Ризотто с белыми грибами"), 
      'title'=>array('EN'=>'Arborio rice, porcini mushrooms', 'RU'=>"Рис арборио, белые грибы"), 
      'price'=> 899,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "",
    ),
    array(
      'id'=> 40,
      'name'=>array('EN'=>'Spaghetti with crab in tomato sauce', 'RU'=>"Спагетти с крабом в томатном соусе"), 
      'title'=>array('EN'=>'Spaghetti, crab, chicken broth, basil, tomato sauce, oil', 'RU'=>"Спагетти, краб, куриный бульон, базилик, соус томатный, масло"), 
      'price'=> 999,
      'count'=> 1,
      'grams'=> 300,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'salads',
    'mini' => false,
    'cat'=>array("EN"=>'Salads',"RU"=>'Салаты'),
    'items' => array(
    array(
      'id'=> 41,
      'name'=>array('EN'=>'Broken cucumber and salmon', 'RU'=>"Битый огурец и лосось"), 
      'title'=>array('EN'=>'Salmon, cucumbers, onions, mixed greens, cashew nuts', 'RU'=>"Лосось, огурцы, лук репчатый, зелень микс, орех кешью"), 
      'price'=> 699,
      'count'=> 1,
      'grams'=> 360,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3491582/25e0dfd69b2e4a4a9b73f952b85df7a4/450x300",
    ),
    array(
      'id'=> 42,
      'name'=>array('EN'=>'Greek salad with kalamata olives', 'RU'=>"Греческий салат с оливками каламата"), 
      'title'=>array('EN'=>'Baku tomatoes, cucumbers, bell peppers, red onions, mixed salad', 'RU'=>"Помидоры бакинские, огурцы, болгарский перец, красный лук, микс салатов"),
      'price'=> 599,
      'count'=> 1,
      'grams'=> 310,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3547279/11fb7fac98ba4b90b0e57f9f59a77f26/450x300",
    ),
    array(
      'id'=> 43,
      'name'=>array('EN'=>'Green Bowl', 'RU'=>"Зеленый боул"),
      'title'=>array('EN'=>'Avocado, cucumber, chicken egg, chuca lettuce, spinach', 'RU'=>"Авокадо, огурец, яйцо куриное, чука салат, шпинат"), 
      'price'=> 499,
      'count'=> 1,
      'grams'=> 170,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3805363/38668bf155ad480288bd1359c6493097/450x300",
    ),
    array(
      'id'=> 44,
      'name'=>array('EN'=>'Avocado shrimp and tomato salad', 'RU'=>"Салат с креветками авокадо и томатами"), 
      'title'=>array('EN'=>'Shrimp, Baku tomatoes, avocado, cilantro, sour cream, olive oil', 'RU'=>"Креветки, помидоры бакинские, авокадо, кинза, сметана, оливковое масло"),
      'price'=> 799,
      'count'=> 1,
      'grams'=> 250,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3559865/16e8aaa2c91d4e1d87a1163fee124891/450x300",
    ),
    array(
      'id'=> 45,
      'name'=>array('EN'=>'Grilled shrimp Caesar', 'RU'=>"Цезарь с креветками на гриле"), 
      'title'=>array('EN'=>'Romano salad leaves, shrimp, cherry tomatoes, parmesan cheese, caesar sauce, wheat baguette croutons', 'RU'=>"Листья салата Романо, креветки, помидоры черри, сыр пармезан, соус цезарь, гренки из пшеничного багета"), 
      'price'=> 599,
      'count'=> 1,
      'grams'=> 250,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3725642/a7d5b0ec3e6b4f209bb066327c3cce68/450x300",
    ),
    array(
      'id'=> 46,
      'name'=>array('EN'=>'Caesar with grilled chicken breast', 'RU'=>"Цезарь с куриной грудкой на гриле"), 
      'title'=>array('EN'=>'Romano salad leaves, chicken fillet, cherry tomatoes, parmesan cheese, sauce', 'RU'=>"Листья салата Романо, куриное филе, помидоры черри, сыр пармезан, соус"),
      'price'=> 499,
      'count'=> 1,
      'grams'=> 250,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3805363/c70b5268269944d4aa2eeccbc8c89f5e/450x300",
    ),
    array(
      'id'=> 47,
      'name'=>array('EN'=>'Nisuaz', 'RU'=>"Нисуаз"), 
      'title'=>array('EN'=>'Tuna fillet, baked potatoes, green beans, olives', 'RU'=>"Филе тунца, картофель запеченный, фасоль стручковая, оливки"), 
      'price'=> 999,
      'count'=> 1,
      'grams'=> 220,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'rawbar',
    'mini' => false,
    'cat' => array("EN"=>'RAW BAR',"RU"=>'RAW BAR'),
    'items' => array(
    array(
      'id'=> 48,
      'name'=>array('EN'=>'Sea urchin', 'RU'=>"Морской ёж"), 
      'title'=>array('EN'=>'Sea urchin, quail egg yolk, Ponzu sauce(1pc.)', 'RU'=>"Морской ёж, желток перепелиного яйца, соус Понзу(1шт.)"), 
      'price'=> 359,
      'count'=> 1,
      'grams'=> 10,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3805363/82fc446f3def42d7bdf6a79840d52018/450x300",
    ),
    array(
      'id'=> 52,
      'name'=>array('EN'=>'Imperial Oyster', 'RU'=>"Устрица императорская"), 
      'title'=>array('EN'=>'Oyster, lemon, wine sauce (1 unit)', 'RU'=>"Устрица, лимон, соус Винный (1шт.)"), 
      'price'=> 359,
      'count'=> 1,
      'grams'=> 10,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3506804/3ba638771e994e14be16bbd17fd88590/450x300",
    ),
    array(
      'id'=> 53,
      'name'=>array('EN'=>'Oyster Pink Jolie', 'RU'=>"Устрица Розовая Джоли"),
      'title'=>array('EN'=>'Oyster, lemon, wine sauce (1 unit)', 'RU'=>"Устрица, лимон, соус Винный (1шт.)"), 
      'price'=> 499,
      'count'=> 1,
      'grams'=> 10,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3781088/56f84fb3422f4c688bc61cb1a893c2c5/450x300",
    ),
    array(
      'id'=> 54,
      'name'=>array('EN'=>'Khasan Oyster', 'RU'=>"Устрица Хасанская"), 
      'title'=>array('EN'=>'Oyster, lemon, wine sauce (1 unit)', 'RU'=>"Устрица, лимон, соус Винный (1шт.)"), 
      'price'=> 359,
      'count'=> 1,
      'grams'=> 10,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3378693/2f86c58f9fa14d4d957448168544b397/450x300",
    ),
    array(
      'id'=> 49,
      'name'=>array('EN'=>'Beef tartar', 'RU'=>"Тартар из говядины"), 
      'title'=>array('EN'=>'Beef loin, capers, mustard, tabasco, olive oil, croutons', 'RU'=>"Говяжья вырезка, каперсы, горчица, табаско, оливковое масло, гренки"),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 160,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3702558/efbdfaa6e41a44e381e6d08b932357ec/450x300",
    ),
    array(
      'id'=> 50,
      'name'=>array('EN'=>'Salmon and avocado tartare', 'RU'=>"Тартар из лосося и авокадо"), 
      'title'=>array('EN'=>'Salmon fillet, avocado, sesame, olive oil, ponzu sauce, strawberries', 'RU'=>"Филе лосося, авокадо, кунжут, оливковое масло, соус понзу, клубника"),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3774488/873d863faa0f45789ce2dba5393d6c05/450x300",
    ),
    array(
      'id'=> 51,
      'name'=>array('EN'=>'Tuna tartar', 'RU'=>"Тартар из тунца"), 
      'title'=>array('EN'=>'Tuna fillet, avocado, guacamole, sesame oil, soy sauce', 'RU'=>"Филе тунца, авокадо, гуакамоле, кунжутное масло, соевый соус"), 
      'price'=> 799,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3436037/74e45e0bf868433489bc5e9545a634f0/450x300",
    ),
    )
    
),
  
    array(
    'data' => 'children',
    'mini' => false,
    'cat'=>array("EN"=>'Children`s menu',"RU"=>'Детское меню' ),
    'items' => array(
    array(
      'id'=> 55,
      'name'=>array('EN'=> 'Beef stroganoff with mashed potatoes', 'RU'=>"Бефстроганов из говядины с картофельным пюре" ),
      'title'=>array('EN'=> 'Beef loin, mashed potatoes, cream sauce', 'RU'=>"Говяжья вырезка, картофельное пюре, сливочный соус" ),
      'price'=> 589,
      'count'=> 1,
      'grams'=> 240,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3774488/730b6bce9f584119a276fb9f20422bf6/450x300",
    ),
    array(
      'id'=> 56,
      'name'=>array('EN'=> 'Chicken cutlets with mashed potatoes', 'RU'=>"Куриные котлеты с картофельным пюре" ),
      'title'=>array('EN'=> 'Minced chicken, mashed potatoes, butter', 'RU'=>"Куриный фарш, картофельное пюре, сливочное масло" ),
      'price'=> 599,
      'count'=> 1,
      'grams'=> 240,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3559865/d81289567aa14454863b5cbe69461918/450x300",
    ),
    array(
      'id'=> 57,
      'name'=>array('EN'=> 'Chicken broth with noodles and vegetables', 'RU'=>"Куриный бульон с лапшой и овощами" ),
      'title'=>array('EN'=> 'Chicken broth, chicken filet, noodles, vegetables', 'RU'=>"Куриный бульон, куриное филе, лапша, овощи" ),
      'price'=> 219,
      'count'=> 1,
      'grams'=> 230,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3436037/93fce62acc254aee95de5b1827dea56a/450x300",
    ),
    array(
      'id'=> 58,
      'name'=>array('EN'=> 'Minestrone', 'RU'=>"Минестроне" ),
      'title'=>array('EN'=> 'Vegetable broth, vegetables', 'RU'=>"Овощной бульон, овощи" ),
      'modifier'=> array(
        "EN"=> array(
          'standard',
          'With chicken meatballs'
        ),
        "RU"=> array(
          'cтандартное',
          'c куриными фрикадельками'
        )
      ),
      'price'=> 229,
      'count'=> 1,
      'grams'=> 240,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3724421/4128d6509dbe49faa7f43205d81a0557/450x300",
    ),
    
    array(
      'id'=> 59,
      'name'=>array('EN'=> 'Penne in cream sauce with parmesan cheese', 'RU'=>"Пенне в сливочном соусе с сыром пармезан" ),
      'title'=>array('EN'=> 'Penne, parmesan cheese, cream sauce', 'RU'=>"Пенне, сыр пармезан, сливочный соус" ),
      'price'=> 249,
      'count'=> 1,
      'grams'=> 210,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3813301/900e522b23a84369b9cd6a96527b6d48/450x300",
    ),
    array(
      'id'=> 60,
      'name'=>array('EN'=> 'Vegetable sticks with cream sauce', 'RU'=>"Овощные палочки с сливочным соусом" ),
      'title'=>array('EN'=> 'Bell peppers, carrots', 'RU'=>"Перец болгарский, морковь"),
      'price'=> 189,
      'count'=> 1,
      'grams'=> 110,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'brusshetta',
    'mini' => false,
    'cat'=>array("EN"=>'Bruschetta',"RU"=>'Брускетты'),
    'items' => array(
    array(
      'id'=> 61,
      'name'=>array('EN'=> 'With Prosciutto and Strachella', 'RU'=>"С Прошутто и Страчеллой" ),
      'title'=>array('EN'=> 'Grain bread, Prosciutto, Strachella cheese, cherry tomatoes, lettuce', 'RU'=>"Хлеб зерновой, Прошутто, сыр Страчелла, помидоры Черри, салат" ),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3593277/5753bda1f86e431db636ba66b1bc757c/450x300",
    ),
    array(
      'id'=> 62,
      'name'=>array('EN'=> 'With crab', 'RU'=>"С крабом" ),
      'title'=>array('EN'=> 'Grain bread, crab meat, tomatoes, Romano salad, Spicy sauce', 'RU'=>"Хлеб зерновой, крабовое мясо, помидоры, салат Романо, Спайси соус" ) ,
      'price'=> 899,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3502800/f9bcd9e54cff443394f97a19aaaf297b/450x300",
    ),
    array(
      'id'=> 63,
      'name'=>array('EN'=> 'With salmon and avocado', 'RU'=>"С лососем и авокадо" ),
      'title'=>array('EN'=> 'Grain bread, lightly salted salmon, avocado, tomato, creamy', 'RU'=>"Хлеб зерновой, лосось слабосоленый, авокадо, помидоры, сливочный" ),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 220,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3436037/a6696af622ca4bfa972e373ad7ea670d/450x300",
    ),
    array(
      'id'=> 64,
      'name'=>array('EN'=> 'With roast beef', 'RU'=>"С ростбифом" ),
      'title'=>array('EN'=> 'Grain bread, roast beef, tomatoes, red onions, mustard, horseradish, olive oil', 'RU'=>"Хлеб зерновой, ростбиф, помидоры, красный лук, горчица, хрен, оливковое" ),
      'price'=> 599,
      'count'=> 1,
      'grams'=> 190,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3504598/687576360af54e0fa44d791c716668ca/450x300",
    ),
    array(
      'id'=> 65,
      'name'=>array('EN'=> 'With tomatoes and avocado', 'RU'=>"С томатами и авокадо" ),
      'title'=>array('EN'=> 'Grain bread, tomatoes, avocado, guacamole sauce, Romano salads, Frise', 'RU'=> "Хлеб зерновой, помидоры, авокадо, соус Гуакамоле, салаты Романо, Фризе"),
      'price'=> 499,
      'count'=> 1,
      'grams'=> 165,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3781088/e561170d1c754343833e9f34e786ef37/450x300",
    ),
    )
),
  
    array(
    'data' => 'sideDishes',
    'mini' => true,
    'cat'=>array("EN"=>'Side dishes',"RU"=>'Гарниры' ),
    'items' => array(
    array(
      'id'=> 66,
      'name'=>array('EN'=> 'Fried potatoes with oyster mushrooms', 'RU'=>"Жареный картофель с вешенками" ),
      'title'=>array('EN'=> 'Potatoes, oyster mushrooms, onions, parsley, garlic oil, salt, pepper', 'RU'=>"Картофель, грибы вешенки, лук, петрушка, чесночное масло, соль, перец" ),
      'price'=> 399,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "",
    ),
    array(
      'id'=> 67,
      'name'=>array('EN'=> 'Roasted spinach with tomatoes', 'RU'=>"Жареный шпинат с томатами" ),
      'title'=>array('EN'=> 'Spinach, garlic oil, cherry tomatoes, salt, pepper', 'RU'=> "Шпинат, чесночное масло, томаты черри, соль, перец"),
      'price'=> 399,
      'count'=> 1,
      'grams'=> 90,
      'img'=> "",
    ),
    array(
      'id'=> 68,
      'name'=>array('EN'=> 'Mashed potatoes', 'RU'=>"Картофельное пюре" ),
      'title'=>array('EN'=> 'Potatoes, butter, cream', 'RU'=>"Картофель, сливочное масло, сливки" ),
      'price'=> 349,
      'count'=> 1,
      'grams'=> 150,
      'img'=> "",
    ),
    array(
      'id'=> 69,
      'name'=>array('EN'=> 'Grilled corn', 'RU'=>"Кукуруза на гриле" ),
      'title'=>array('EN'=> 'Corn', 'RU'=>"Кукуруза" ),
      'price'=> 399,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "",
    ),
    array(
      'id'=> 70,
      'name'=>array('EN'=> 'Asparagus', 'RU'=>"Спаржа" ),
      'title'=>array('EN'=> 'Asparagus, olive oil', 'RU'=>"Спаржа, оливковое масло" ),
      'price'=> 499,
      'count'=> 1,
      'grams'=> 100,
      'img'=> "",
    ),
    )
),
  
  
    array(
    'data' => 'meatPoultry',
    'mini' => false,
    'cat'=>array("EN"=>'Meat and poultry',"RU"=>'Мясо и птица' ),
    'items' => array(
    array(
      'id'=> 71,
      'name'=>array('EN'=> 'Asian beef with rice', 'RU'=>"Говядина по-азиатски с рисом" ),
      'title'=>array('EN'=> 'Beef loin, rice, pea pods, soy sprouts, Asian sauce', 'RU'=>"Говяжья вырезка, рис, стручки гороха, ростки сои, соус азиатский" ),
      'price'=> 899,
      'count'=> 1,
      'grams'=> 280,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3377781/0ef9d244a4de42268242ae341246337e/450x300",
    ),
    array(
      'id'=> 72,
      'name'=>array('EN'=> 'Chicken curry with rice', 'RU'=>"Курица карри с рисом" ),
      'title'=>array('EN'=> 'Chicken fillet, rice, curry sauce', 'RU'=>"Куриное филе, рис, карри соус" ),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 280,
      'img'=> "https://avatars.mds.yandex.net/get-eda/2415806/5369455898bc4c4d869b3e4eb81f4f5d/450x300",
    ),
    array(
      'id'=> 73,
      'name'=>array('EN'=> 'Ribeye steak with grilled corn', 'RU'=>"Рибай стейк с кукурузой на гриле" ),
      'title'=>array('EN'=> 'Beef loin, corn cob', 'RU'=>"Говяжья вырезка, початок кукурузы" ),
      'price'=> 2599,
      'count'=> 1,
      'grams'=> 380,
      'img'=> "",
    ),
    array(
      'id'=> 74,
      'name'=>array('EN'=> 'Roe deer stew with mashed potatoes', 'RU'=>"Томленая косуля с картофельным пюре" ),
      'title'=>array('EN'=> 'Tender roe meat, mashed potatoes', 'RU'=>"Нежное мясо косули, картофельное пюре" ),
      'price'=> 1199,
      'count'=> 1,
      'grams'=> 240,
      'img'=> "",
    ),
    array(
      'id'=> 75,
      'name'=>array('EN'=> 'Grilled filet mignon with zucchini', 'RU'=>"Филе миньон с цукини на гриле" ),
      'title'=>array('EN'=> 'Beef loin, zucchini, mushroom sauce, vegetable oil', 'RU'=>"Говяжья вырезка, цукини, грибной соус, масло растительное" ),
      'price'=> 1699,
      'count'=> 1,
      'grams'=> 350,
      'img'=> "",
    ),
    )
),
  
    array(
    'data' => 'snacks',
    'mini' => false,
    'cat'=>array("EN"=>'Snacks',"RU"=>'Закуски'),
    'items' => array(
    array(
      'id'=> 76,
      'name'=>array('EN'=> 'Meat Plateau', 'RU'=>"Мясное плато"),
      'title'=>array('EN'=> 'Prosciutto, roast beef, salami', 'RU'=>"Прошутто, ростбиф, салями" ),
      'price'=> 1299,
      'count'=> 1,
      'grams'=> 150,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3506707/3a4692592f0e4b5a9100d490f02a0974/450x300",
    ),
    array(
      'id'=> 77,
      'name'=>array('EN'=> 'Chicken liver pate with brioche', 'RU'=>"Паштет из куриной печени с бриошью" ),
      'title'=>array('EN'=> 'Chicken liver pate, brioche, fig jam', 'RU'=>"Паштет из куриной печени, бриошь, джем из инжира" ),
      'price'=> 399,
      'count'=> 1,
      'grams'=> 120,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3420935/e586c76c33c445259979def0c227b0fd/450x300",
    ),
    array(
      'id'=> 78,
      'name'=>array('EN'=> 'Antipasti Set', 'RU'=> "Сет Антипасти"),
      'title'=>array('EN'=> 'Kalamata olives, sun-dried tomatoes, artichokes', 'RU'=>"Оливки каламата, вяленые томаты, артишоки" ),
      'price'=> 1199,
      'count'=> 1,
      'grams'=> 250,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3504598/5f54f90f71ff42eeb2bcf0cd3c58a9cc/450x300",
    ),
    array(
      'id'=> 79,
      'name'=>array('EN'=> 'Cheese Plateau', 'RU'=>"Сырное плато" ),
      'title'=>array('EN'=> 'Gorgonzola, Brie, Parmesan, nuts, dried fruit, grapes and honey', 'RU'=>"Горгонзола, бри, пармезан, орехи, сухофрукты, виноград и мед" ),
      'price'=> 1399,
      'count'=> 1,
      'grams'=> 330,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3454897/71660cfbea344b4fbf02ce26adde63b3/450x300",
    ),
),
  
   array(
    'data' => 'fishSeafood',
    'mini' => false,
    'cat'=>array("EN"=>'Fish and seafood',"RU"=>'Рыба и морепродукты' ),
    array(
      'id'=> 80,
      'name'=>array('EN'=> 'Grilled shrimp with spicy sauce', 'RU'=>"Креветки на гриле с соусом спайси") ,
      'title'=>array('EN'=> 'Shrimp, soy sauce, sesame oil, spicy sauce, sesame seeds, bamboo leaf', 'RU'=>"Креветки, соевый соус, масло кунжутное, спайси соус, кунжут, лист бамбука"),
      'price'=> 799,
      'count'=> 1,
      'grams'=> 150,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3583740/eb737a5203734f5e8ec1557bf2c8ef49/450x300",
    ),
    array(
      'id'=> 81,
      'name'=>array('EN'=> 'Mussels in wine sauce', 'RU'=>"Мидии в винном соусе") ,
      'title'=>array('EN'=> 'Mussels, chicken broth, wine, coconut milk, rosemary, thyme, cilantro', 'RU'=>"Мидии, куриный бульон, вино, кокосовое молоко, розмарин, тимьян, кинза"),
      'price'=> 699,
      'count'=> 1,
      'grams'=> 500,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3593277/88a00787ad4647a1a789d184cd12667a/450x300",
    ),
   
    array(
      'id'=> 125,
      'name'=>array('EN'=> 'Salmon steak with vegetable salsa', 'RU'=>"Стейк лосося с овощной сальсой"),
      'title'=>array('EN'=> 'Salmon fillet, tomato salsa, avocado, cucumber vegetable oil', 'RU'=>"Филе лосося, сальса из томатов, авокадо, огурец масло растительное"),
      'modifier'=>array('EN'=>array('on the grill', 'steamed'), 'RU'=>array('на гриле','на пару')),
      'price'=> 1199,
      'count'=> 1,
      'grams'=> 200,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3514991/e93a9c2fb26d46e9bfc020cead3f934e/450x300",
    ),
   array(
    'id'=> 2342,
    'name'=> array('EN'=> 'Sea bass fillet with red couscous', 'RU'=> 'Филе сибаса с красным кускусом'),
    'title'=> array('EN'=> 'Sea bass fillet, zucchini, cilantro, pesto sauce, olive oil, tomato', 'RU'=> 'Сибас филе, цукини, кинза, соус песто, масло оливковое, томат'),
    'price'=> 899,
    'count'=> 1,
    'grams'=> 300,
    'img'=> "/assets/items/2342.jpg"
   ),
   array(
    'id'=> 2343,
    'name'=> array('EN'=> 'Black cod on a bed of spinach', 'RU'=> 'Черная треска на подушке из шпината'),
    'title'=> array('EN'=> 'Baked black cod fillet served on a bed of poached spinach surrounded by walnut sauce and almond slices', 'RU'=> 'Запеченное филе черной трески подается на подушке из припущенного шпината в окружении орехового соуса и слайсов миндаля'),
    'price'=> 890,
    'count'=> 1,
    'grams'=> 180,
    'img'=> "/assets/items/2343.jpg"
      )
    )
   ),
  
   array(
    'data'=> 'soap',
    'mini' => false,
    'cat'=>array("EN"=>'Soups',"RU"=>'Супы' ),
    'items' => array(
    array(
      'id'=> 84,
      'name'=>array('EN'=> 'Borscht with roe deer', 'RU'=>"Борщ с косулей") ,
      'title'=>array('EN'=> 'Red borscht with meat, tender roe and sour cream', 'RU'=>"Красный борщ с мясом, нежной косули и сметаной") ,
      'price'=> 499,
      'count'=> 1,
      'grams'=> 280,
      'img'=> "https://avatars.mds.yandex.net/get-eda/1962206/f2e77638b023448eb2e6a0689a18733c/450x300",
    ),
    array(
      'id'=> 85,
      'name'=>array('EN'=> 'Cream soup of wild mushrooms', 'RU'=>"Крем-суп из лесных грибов") ,
      'title'=>array('EN'=> 'Champignons, porcini mushrooms, cream, rice chips', 'RU'=>"Шампиньоны, белые грибы, сливки, рисовые чипсы") ,
      'price'=> 449,
      'count'=> 1,
      'grams'=> 270,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3439767/a990b9337c5941fb8680ed16d95aa479/450x300",
    ),
    array(
      'id'=> 86,
      'name'=>array('EN'=> 'Chicken noodle soup', 'RU'=>"Суп-лапша из цыпленка") ,
      'title'=>array('EN'=> 'Chicken broth, vermicelli, chicken fillet, quail egg, herbs', 'RU'=>"Куриный бульон, вермишель, куриное филе, перепелиное яйцо, зелень") ,
      'price'=> 399,
      'count'=> 1,
      'grams'=> 450,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3725642/9f060f3824d44083bbdc5dae565dce9f/450x300",
    ),
    array(
      'id'=> 87,
      'name'=>array('EN'=> 'Tom Yum with seabass and seafood', 'RU'=>"Том ям с сибасом и морепродуктами") ,
      'title'=>array('EN'=> 'Coconut milk, mussels, shrimp, sea bass, tomatoes, rice, mushrooms', 'RU'=>"Кокосовое молоко, мидии, креветки, сибас, помидоры, рис, грибы") ,
      'price'=> 799,
      'count'=> 1,
      'grams'=> 580,
      'img'=> "https://avatars.mds.yandex.net/get-eda/3504598/5007287a0a8a4748b03272697031b647/450x300",
    ),
    )
),
   
  
    array(
    'data'=> 'lenten',
    'mini' => false,
    'cat'=>array("EN"=>'Lenten',"RU"=>'Постное'),
    'items' => array(
    array(
      'id'=> 91,
      'name'=>array('EN'=> 'Baked yams with mushrooms and zazaki sauce', 'RU'=>"Запеченный батат с грибами и соусом дзадзики"),
      'title'=>array('EN'=> 'Batat, mushrooms, oyster mushrooms, ceps, vegetable oil, garlic puree, cucumbers, lean sour cream, olive oil, truffle oil, pearl onions, green onions, ground olives, dill, salt, pepper, thyme', 'RU'=>"Батат, шампиньоны, вешенки, белые грибы, масло растительное, чесночное пюре, огурцы, постная сметана, масло оливковое, масло трюфельное, жемчужный лук, лук зеленый, земля из маслин, укроп, соль, перец, тимьян"),
      'price'=> 590,
      'count'=> 1,
      'grams'=> 270,
      'img'=> "https://eda.yandex.ru/images/3208959/0228a35b95534b8e8a2a9b3f66b1e0b4-450x300.jpeg",
    ),  array(
      'id'=> 92,
      'name'=>array('EN'=> 'Pistachio cream with coconut milk', 'RU'=>"Фисташковый крем на кокосовом молоке"),
      'title'=>array('EN'=> 'Cream of coconut, pistachio paste, powdered sugar, lean cookie crumb, blueberries, freeze-dried raspberries, sunflower seeds', 'RU'=>"Сливки из кокоса, фисташковая паста, сахарная пудра, крошка из постного печенья, голубика, малина сублимированная, семечка подсолнечника"),
      'price'=> 370,
      'count'=> 1,
      'grams'=> 120,
      'img'=> "https://eda.yandex.ru/images/3337779/dba9330876324cf2b9fc5837dc33ad9f-450x300.jpeg",
    ),  array(
      'id'=> 93,
      'name'=>array('EN'=> 'Baked zucchini with beet coulis', 'RU'=>"Печёный кабачок со свекольным кули"),
      'title'=>array('EN'=> 'Beets, avocado, mint, cilantro, zucchini, mini spinach, chuka, borado bread chips, kimchi sesame, garlic fraiche, lean sour cream, pumpkin puree, sunflower seeds, olive oil ground, olive oil, salt, pepper, zatar, honey', 'RU'=>"Свекла, авокадо, мята, кинза, кабачки, мини шпинат, чука, чипсы из бородинского хлеба, кунжут с кимчи, чесночный фреш, сметана постная, пюре тыквы, семечки подсолнечника, земля из маслин, масло оливковое, соль, перец, затар, мёд"),
      'price'=> 570,
      'count'=> 1,
      'grams'=> 225,
      'img'=> "https://eda.yandex.ru/images/3667559/f78601f42dd94e2fa9788763a06550f2-450x300.jpeg",
    ), array(
      'id'=> 94,
      'name'=>array('EN'=> 'Vegetable salad with your choice of dressing', 'RU'=>"Овощной салат с заправкой на выбор"),
      'title'=>array('EN'=> 'Cucumber, tomato, bell pepper, parsley, dill, green onion, fresh basil, red onion, tajas olives, olive oil, salt, black pepper, provan herbs', 'RU'=>"Огурец, помидор, болгарский перец, петрушка, укроп, лук зелёный, базилик свежий, лук красный, оливки таджасские, масло оливковое, соль, перец черный, прованские травы"),
      'price'=> 590,
      'modifier'=> array(
        'RU'=>array(
          'c оливковым маслом',
          'c ароматным маслом',
          'c постной сметаной: 100₽'
        ),
        'EN'=> array(
          'with olive oil',
          'with fragrant oil',
          'with lean sour cream: 100₽'
        )
      ),
      'count'=> 1,
      'grams'=> 188,
      'img'=> "https://eda.yandex.ru/images/3724421/cd721dd431634672b6980a0c65df1da0-450x300.jpeg",
    ),  array(
      'id'=> 95,
      'name'=>array('EN'=> 'Lentil cream soup with artichokes and pickled onions', 'RU'=>"Крем-суп из чечевицы с артишоками и маринованным лучком"),
      'title'=>array('EN'=> 'Lentils, carrots, onions, potatoes, artichokes, pearl onions, green onions, seeds, ground olives, olive oil, vegetable oil, garlic, salt, pepper', 'RU'=>"Чечевица, морковь, лук репчатый, картофель, артишоки, лук жемчужный, лук зеленый, семечки, земля из маслин, оливковое масло, масло растительное, чеснок, соль, перец"),
      'price'=> 420,
      'count'=> 1,
      'grams'=> 330,
      'img'=> "https://eda.yandex.ru/images/3580810/96ad18ccda1d42e3b3949d156dbe14f1-450x300.jpeg",
    ),
    array(
      'id'=> 96,
      'name'=>array('EN'=> 'Hummus with grilled broccoli', 'RU'=>"Хумус с брокколи гриль"),
      'title'=>array('EN'=> 'Chickpeas, tahini, ground cumin, lemon juice, broccoli, olive oil, sea salt, slivered almonds, zatar, sesame oil, sunflower and pumpkin seeds, microgreens', 'RU'=>"Нут, тахини, кумин молотый, лимонный сок, брокколи, масло оливковое, соль морская, миндаль слайс, затар, масло кунжутное, семечка подсолничника и тыквы, микрозелень"),
      'price'=> 490,
      'count'=> 1,
      'grams'=> 270,
      'img'=> "https://eda.yandex.ru/images/3106738/aa1e9c65855440c8bfc59cc905a5db77-450x300.jpeg",
    ),
    array(
      'id'=> 97,
      'name'=>array('EN'=> 'Crispy falafel with babaganoush, dzadziki and fresh tomatoes', 'RU'=>"Хрустящий фалафель с бабагануш, дзадзики и свежими томатами"),
      'title'=>array('EN'=> 'Chickpeas, spinach, truffle paste, truffle oil, breadcrumbs, wheat flour, coconut milk, baked eggplant, tomatoes, cilantro, parsley, green onions, garlic puree, cucumber, lean sour cream, olive seeds, tomatoes, basil, black pepper, zatar, olive oil, salt', 'RU'=>"Нут, шпинат, трюфельная паста, масло трюфельное, панировочные сухари, мука пшеничная, молоко кокосовое, баклажан печёный, томаты, кинза, петрушка, лук зелёный, чесночное пюре, огурец, постная сметана, земля из маслин, помидоры, базилик, перец черный, затар, масло оливковое, соль"),
      'price'=> 690,
      'count'=> 1,
      'grams'=> 340,
      'img'=> "https://eda.yandex.ru/images/3682162/00c3527cf7ee4de79f4ef93660ff3ed9-450x300.jpeg",
    )
    )
  )
    ];

if($_SERVER['REQUEST_METHOD'] === 'GET'){
$json = json_encode($items);

header('Content-Type: application/json');


echo $json;
};



?>