import Head from 'next/head';
import dynamic from 'next/dynamic';
import { useEffect } from 'react';
import { useLayoutLogic } from '@/layout/useLayoutLogic';
import Descriptor from '@/components/ui/descriptor/descriptor';
import Corousel from '@/components/ui/carousel/carousel';
import MainMenu from '@/components/ui/MenuBlock/MenuBlock';
import styles from './mainPage.module.css';


const Contacts = dynamic(() => import('../../ui/contacts/contacs'));



export default function HomePage() {
    const { scroll, toContact, contactsRef } = useLayoutLogic();

    useEffect(() => {
        let timeout: any;
        if (toContact) {
            timeout = setTimeout(() => {
                scroll();
            }, 200);
        }
        return () => {
            clearTimeout(timeout);
        };
    }, [toContact]);

    return (
        <>
            <Head>
                <title>Адрес39</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="yandex-verification" content="b664a6bb74ee0f23" />
                <meta name="robots" content="index, follow" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <div className={styles.mainContent}>
                    <Descriptor />
                    <div className={styles.corouselMain}>
                        <Corousel />
                    </div>
                </div>
                <div
                    style={{ backgroundColor: '#fff', padding: '20px 0 20px' }}
                >
                    <MainMenu />
                </div>
                <Contacts refs={contactsRef} />
            </div>
        </>
    );
}