import styles from './menu.module.css';
import {motion} from 'framer-motion'
import MenuItem from "@/components/ui/menuItem/MenuItem";
import { useAppSelector } from "@/common/hooks/useRedux";
import { MainMenuRU } from "@/lang/ru";
import { MainMenuEN } from "@/lang/en";
import Head from 'next/head';
function Menu() {
	const lang = useAppSelector(state => state.languageSlice.language)

	const menuPageArr = lang === 'EN' ? MainMenuEN : MainMenuRU
	
	return (
		<>
		<Head>
            	<title>Меню | Адрес39</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="robots" content="index, follow" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
          </Head>
		<motion.div
			initial={{opacity: 0}}
			animate={{opacity: 1}}
		className={styles.wrapper}>
			<div className={styles.flex}>
				{menuPageArr.map((i, ind) => {		
					return <MenuItem key={ind} name={i.name} img={i.img} src={i.src} />;
				})}
			</div>
	</motion.div>
	</>
	);
}

export default Menu;
